import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

/**
 * Fingerprint of the ruleset THIS process has loaded.
 *
 * Two copies of the scanner run in this project: the API (long-lived, under
 * PM2) and whatever script is scanning right now. A rule change that is not
 * followed by a restart leaves the API signing verdicts from the old rules —
 * and the API's verdict is the one that gets anchored, permanently, on somebody
 * else's published package. A report generated by the new rules then describes
 * a registry that disagrees with it.
 *
 * The hash is read from the rule sources at import time, so it is the rules in
 * memory, not the rules on disk.
 */
const SOURCES = ['engine.js', 'mcp.js'];

const h = createHash('sha256');
for (const f of SOURCES) h.update(readFileSync(fileURLToPath(new URL(f, import.meta.url))));

export const rulesVersion = h.digest('hex').slice(0, 16);
